### ISSUE TITLE
Conflicts with protected and private ordering

### ISSUE THREAD

**Issue by bmulholland** [jeromedalbert/rubocop-obsession#4]
When method A is used first, and private, and method B is used second, and protected, the method order rules conflict with [Layout/ClassStructure](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/ClassStructure)'s default: protected should come before private.

**Comment by bmulholland** [comment]
I suspect more complex scenarios would have issues too -- what if there's A/B/C/D usage, weaving between private and protected?

**Comment by jeromedalbert** [comment]
These are all good points! I rarely use `protected` so I never ran into those cases, but here are a few thoughts:

- Maybe method ordering shouldn't apply for private methods calling protected methods. And maybe likewise for protected methods calling private methods. I need to flesh this idea out a bit more.
- Or the protected section could be completely ignored if there is a private section. But this means the protected section wouldn't be ordered, so probably not the best.

**Comment by bmulholland** [comment]
Both those ideas seem viable. I also rarely use protected, especially together with private, but it does make it hard to even figure out what a readable order would be. Absent an opinion on what the goal should even be, disabling some aspects seem reasonable.

**Comment by jeromedalbert** [comment]
Fixed in https://github.com/jeromedalbert/rubocop-obsession/commit/f5c71c4d736499d5034f8244622992981d1636ac and released a new version.

The cop won't check the order of protected methods when there are both a protected section and a private section. This should take care of the use cases you mentioned.

Do not hesitate to file a new issue if you notice anything else!
